apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/part-of: kube-prometheus
  name: blackbox-exporter
  namespace: {{ .Values.common.namespace | default "monitoring" }}
spec:
  ports:
  - name: https
    port: 9115
    targetPort: https
  - name: probe
    port: {{ .Values.blackboxExporter.port | default "19115" }}
    targetPort: http
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/part-of: kube-prometheus
