apiVersion: v1
data:
  config.yml: |
{{ .Values.blackboxExporter.config | nindent 4 }}  
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/part-of: kube-prometheus
  name: blackbox-exporter-configuration
  namespace: {{ .Values.common.namespace | default "monitoring" }}
