apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
  name: grafana
  namespace: {{ .Values.common.namespace | default "monitoring" }}
spec:
  ports:
  - name: http
    port: {{ .Values.grafana.port | default "3000" }}
    targetPort: http
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
