apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
  name: k8s
  namespace: {{ .Values.common.namespace | default "monitoring" }}
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: {{ .Values.common.namespace | default "monitoring" }}
      port: web
  enableFeatures: []
  externalLabels: {{ .Values.prometheus.externalLabel | default "test" }}
  image: {{ .Values.prometheus.image | default "quay.io/prometheus/prometheus:v2.49.1" }}
{{- if .Values.common.nodeSelector }}
  nodeSelector: {{ toYaml .Values.common.nodeSelector | nindent 4 }}
{{- end }}
{{- if .Values.common.tolerations }}
  tolerations: {{ toYaml .Values.common.tolerations | nindent 4 }}
{{- end }}
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: {{ .Values.common.replicasCount | default "3" }}
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector: {{ .Values.common.namespace | default "monitoring" }}
  ruleSelector: {}
  scrapeConfigNamespaceSelector: {{ .Values.common.namespace | default "monitoring" }}
  scrapeConfigSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {{ .Values.common.namespace | default "monitoring" }}
  serviceMonitorSelector: {}