apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: ssh-exporter
  name: ssh-exporter
  namespace: {{ .Values.namespace | default "monitoring" }}
spec:
  ports:
  - name: http
    port:  {{ .Values.port | default "9312" }}
    targetPort: http