apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: ssh-exporter
  name: ssh-config
  namespace: {{ .Values.namespace | default "monitoring" }}
data:
  config.yaml: |
    modules:  
{{ .Values.ConfigMap.FunctionKey | indent 6 }}
{{ .Values.ConfigMap.FunctionKey | indent 8 }}