apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: test1
  name: test1
  namespace: default
stringData:
  vminfo: |
    test1 10.22.3.4 aaa waji /app
    test2 10.22.3.5 bbb waji /app
    test3 10.22.3.6 ccc waji /app
    10.22.3.8 test4 zzz waji /app    