apiVersion: v1
kind: Pod
metadata:
  name: example-pod-nonseal
spec:
  containers:
  - name: example-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /tmp/ # directory
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: test10